apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-stxp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-stxp
    app.kubernetes.io/part-of: tkrw-pr712-0075-0065-app
  name: devfile-sample-stxp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-stxp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-stxp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-stxp@sha256:3bbc7f2cf00e0c3a4d09d5ac9ec43fea78cc0bde4343c714cc7c27d65961135a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
