apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-stxp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-stxp@sha256:3bbc7f2cf00e0c3a4d09d5ac9ec43fea78cc0bde4343c714cc7c27d65961135a
        name: my-nodejs
        resources: {}
status: {}
